name: Workflow Demo

on: 
  push:
  workflow_dispatch:

env:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create a text file
      run: echo "Hello, world!" > hello.txt
