name: De[pcheck]

on: 
  workflow_dispatch:
  push:
    branches:
      - 'branch-b'

env:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    Build_Docker_Image:
      name: Build Docker Image
      runs-on:
        - ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }} .
        shell: bash

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}"
          severity: 'CRITICAL'
          format: 'template'
          template: "@/contrib/html.tpl"
          exit-code: 1
          hide-progress: true


      - run: ls -ltr

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.1.0
        with:
          if-no-files-found: ignore
          name: Trivy Image Critical Vul Report
          path: "."


    # Trivy_Vulnerability_Scanner:
    #   name: Trivy Vulnerability Scanner
    #   runs-on:
    #     - ubuntu-latest
    #   needs: Build_Docker_Image
    #   steps:
    #   - name: checkout
    #     uses: actions/checkout@v4.1.0
    #   - name: sh
    #     shell: bash
    #     run: trivy image siddharth67/solar-system:${{ github.sha }}ICAL --exit-code 1 --quiet --format json -o trivy-image-CRITICAL-results.json
    #   - name: sh
    #     shell: bash
    #     run: trivy convert --format template --template "@/usr/local/share/trivy/templates/html.tpl" --output trivy-image-CRITICAL-results.html trivy-image-CRITICAL-results.json
    #   - name: Upload Artifacts
    #     uses: actions/upload-artifact@v4.1.0
    #     with:
    #       if-no-files-found: ignore
    #       name: Trivy Image Critical Vul Report
    #       path: "."

    # Unit_Testing:
    #   name: Unit Testing
    #   runs-on:
    #     - ubuntu-latest
    #   container:
    #     image: node:24
    #   steps:
    #   - name: checkout
    #     uses: actions/checkout@v4
    #   - run: npm i --no-audit
    #   - uses: nick-fields/retry@v3
    #     with:
    #       timeout_minutes: 60
    #       max_attempts: 2
    #       retry_on: error
    #       command: npm test
    #   - name: Publish Test Results
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: test-results
    #       path: test-results.xml
    #   - name: checkout
    #     uses: actions/checkout@v4.1.0
    # Code_Coverage:
    #   name: Code Coverage
    #   runs-on:
    #     - ubuntu-latest
    #   container:
    #     image: node:24
    #   needs: Unit_Testing
    #   steps:
    #   - name: checkout
    #     uses: actions/checkout@v4.1.0
    #   - name: Install dependencies
    #     run: npm install --no-audit
    #     shell: bash
    #   - name: Check Code Coverage
    #     continue-on-error: true
    #     run: npm run coverage
    #     shell: bash
    #   - name: Upload Artifacts
    #     uses: actions/upload-artifact@v4.1.0
    #     with:
    #       if-no-files-found: ignore
    #       name: Code Coverage HTML Report
    #       path: coverage/lcov-report

      # - name: Depcheck
      #   uses: dependency-check/Dependency-Check_Action@main
      #   continue-on-error: true
      #   id: Depcheck
      #   with:
      #     project: test
      #     path: "."
      #     format: ALL
      #     out: reports
      #     args: "--failOnCVSS 4"



      # - name: Depcheck
      #   uses: dependency-check/Dependency-Check_Action@main
      #   continue-on-error: true
      #   id: Depcheck
      #   with:
      #     project: 'test'
      #     path: '.'
      #     format: 'ALL'
      #     out: 'reports' # this is the default, no need to specify unless you wish to override it
      #     args: >
      #       --failOnCVSS 3
      #       --enableRetired
      # - name: Upload Test results
      #   uses: actions/upload-artifact@master
      #   with:
      #      name: Depcheck report
      #      path: ${{github.workspace}}/reports